apiVersion: v1
kind: Service
metadata:
  name: {{ template "minio.name" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ template "minio.name" . }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
  {{- range $key, $value := .Values.minio.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "minio.name" . }}
    release: {{ template "minio.name" . }}