apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.name" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ template "nginx.name" . }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  {{- range $key, $value := .Values.nginx.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "nginx.name" . }}
    release: {{ template "nginx.name" . }}
