apiVersion: v1
kind: Service
metadata:
  name: {{ template "adminapi.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "adminapi.name" . }}
    chart: {{ template "adminapi.chart" . }}
    release: {{ template "adminapi.name" . }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
  {{- range $key, $value := .Values.admin.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "adminapi.name" . }}
    release: {{ template "adminapi.name" . }}