apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
  name: health
data:
  ping_local.sh: |-
    response=$(
      redis-cli \
        -a Dctm@1234 \
        -h localhost \
        -p 6379 \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi