replicaCount: 1

podDisruptionBudget: |
  maxUnavailable: 1

terminationGracePeriodSeconds: 30

strategy: 
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

admin:
  nameOverride: "adminapi"
  image:
    repository: hzent.amberdata.cn:8082/adminapi
    tag: V5.5.0-release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -agentlib:jdwp=transport=dt_socket,address=48001,server=y,suspend=n
    - -jar
    - /adminapi.jar
  service:
    name: adminapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8001
        port: 8001
        protocol: TCP
      rpcport: 
        targetPort: 22200
        port: 22200
        protocol: TCP
      jvmport:
        targetPort: 48001
        port: 48001
        protocol: TCP    
  resources: 
  volumes:
    - name: logs
      hostPath:
        path: /logs    
  volumeMounts:
    - name: logs
      mountPath: /logs        
  priorityClassName: ""       
  tolerations: []    
  affinity: 
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - adminapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

metadata: 
  nameOverride: "metadataapi" 
  image:
    repository: hzent.amberdata.cn:8082/metadataapi
    tag: V6.0.0-release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -jar
    - /metadataapi.jar  
  service:
    name: metadataapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8002
        port: 8002
        protocol: TCP
      rpcport: 
        targetPort: 22201
        port: 22201
        protocol: TCP  
  resources:   
  volumes:
    - name: logs
      hostPath:
        path: /logs  
    - name: tmp
      hostPath:
        path: /tmp    
  volumeMounts:
    - name: logs
      mountPath: /logs 
    - name: tmp
      mountPath: /tmp       
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - metadataapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname


erms: 
  nameOverride: "ermsapi" 
  image:
    repository: hzent.amberdata.cn:8082/ermsapi
    tag: V6.5.0-RELEAS
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -agentlib:jdwp=transport=dt_socket,address=8888,server=y,suspend=n
    - -jar
    - /ermsapi.jar 
  service:
    name: ermsapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8010
        port: 8010
        protocol: TCP
      rpcport: 
        targetPort: 22204
        port: 22204
        protocol: TCP  
  resources: 
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime  
    - name: logs
      hostPath:
        path: /logs  
    - name: tmp
      hostPath:
        path: /tmp    
  volumeMounts:
    - name: logs
      mountPath: /logs 
    - name: tmp
      mountPath: /tmp 
    - name: time
      mountPath: /etc/localtime
      readOnly: true            
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - ermsapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

dataarchives: 
  nameOverride: "dataarchivesapi" 
  image:
    repository: hzent.amberdata.cn:8082/dataarchivesapi
    tag: V5.0.2-20220719-Release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -jar
    - /dataarchivesapi.jar
  service:
    name: dataarchivesapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8013
        port: 8013
        protocol: TCP
      rpc:
        targetPort: 22213
        port: 22213
        protocol: TCP
  resources: 
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime
    - name: logs
      hostPath:
        path: /logs  
    - name: tmp
      hostPath:
        path: /tmp    
  volumeMounts:
    - name: logs
      mountPath: /logs 
    - name: tmp
      mountPath: /tmp 
    - name: time
      mountPath: /etc/localtime
      readOnly: true            
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - dataarchivesapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

search:
  nameOverride: "searchapi"
  image:
    repository: hzent.amberdata.cn:8082/searchapi
    tag: 6.0.0-20220730-Release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -jar
    - /searchapi.jar
  service:
    name: searchapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8008
        port: 8008
        protocol: TCP
      rpcport: 
        targetPort: 22205
        port: 22205
        protocol: TCP
  resources:    
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime
    - name: logs
      hostPath:
        path: /logs    
  volumeMounts:
    - name: time
      mountPath: /etc/localtime
      readOnly: true  
    - name: logs
      mountPath: /logs        
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - searchapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

validator:
  nameOverride: "validatorapi"
  image:
    repository: hzent.amberdata.cn:8082/validatorapi
    tag: V6.0.0-20220803-Release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -jar
    - /validatorapi.jar
  service:
    name: validatorapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8003
        port: 8003
        protocol: TCP    
      rpcport:
        targetPort: 22209
        port: 22209
        protocol: TCP
  resources: 
  volumes:
    - name: logs
      hostPath:
        path: /logs
    - name: time
      hostPath: 
        path: /etc/localtime    
  volumeMounts:
    - name: logs
      mountPath: /logs
    - name: time
      mountPath: /etc/localtime
      readOnly: true         
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - validatorapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

datart:
  nameOverride: "datartapi"
  image:
    repository: hzent.amberdata.cn:8082/datartapi
    tag: V1.1.3-20220726-Release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
  service:
    name: datartapi
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8070
        port: 8070
        protocol: TCP
  resources:  
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime
    - name: logs
      hostPath:
        path: /logs
  volumeMounts:
    - name: time
      mountPath: /etc/localtime
      readOnly: true  
    - name: logs
      mountPath: /logs
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - datartapi
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname

dataflow:
  nameOverride: "dataflow"
  image:
    repository: hzent.amberdata.cn:8082/amber-dataflow
    tag: 1.16.3
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NIFI_WEB_HTTP_PORT
      value: "8090"    
  command:
  service:
    name: dataflow
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8090
        port: 8090
        protocol: TCP
  resources:  
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime
  volumeMounts:
    - name: time
      mountPath: /etc/localtime
      readOnly: true
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - dataflow
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname


docview:
  nameOverride: "docview"
  image:
    repository: hzent.amberdata.cn:8082/docview
    tag: "4.0"
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
  command:
    - nginx
    - -g
    - daemon off;
  service:
    name: docview
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      http:
        targetPort: 7004
        port: 7004
        protocol: TCP
  resources:    
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime  
  volumeMounts:
    - name: time
      mountPath: /etc/localtime
      readOnly: true   
  priorityClassName: ""       
  tolerations: []    
  affinity: 
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - docview
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname


osprey: 
  nameOverride: "osprey" 
  image:
    repository: hzent.amberdata.cn:8082/osprey
    tag: V5.0.0-20210420-Release
    imagePullPolicy: IfNotPresent
    imagePullSecrets: 
      - name: dev
  env: 
    - name: NACOS_NAMESPACE
      value: "amberdata"    
  command:
    - java
    - -D${NACOS_NAMESPACE}
    - -jar
    - -Xms2048m
    - -Xmx2048m
    - /osprey.jar
  service:
    name: osprey
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      apiport:
        targetPort: 8004
        port: 8004
        protocol: TCP
      rpcport:
        targetPort: 22206
        port: 22206
        protocol: TCP
  resources: 
  volumes:
    - name: time
      hostPath: 
        path: /etc/localtime
    - name: logs
      hostPath:
        path: /logs
  volumeMounts:
    - name: logs
      mountPath: /logs
    - name: time
      mountPath: /etc/localtime
      readOnly: true            
  priorityClassName: ""       
  tolerations: []    
  affinity: {}
    # nodeAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       preference:
    #         matchExpressions:
    #           - key: node-role.kubernetes.io/worker
    #             operator: In
    #             values:
    #               - ''
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app
    #             operator: In
    #             values:
    #               - docview
    #       namespaces:
    #         - app
    #       topologyKey: kubernetes.io/hostname