apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.name" . }}-config
  labels:
    app: {{ template "kibana.name" . }}
    release: {{ template "kibana.name" . }}
data:
{{ toYaml .Values.kibana.kibanaConfig | indent 4 }}
